# Generated by Django 4.0 on 2021-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheely', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
