# Generated by Django 4.0 on 2021-12-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheely', '0004_alter_color_options_alter_size_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.IntegerField()),
                ('stance', models.CharField(max_length=255)),
                ('time_skating', models.IntegerField()),
            ],
        ),
    ]
